AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWSLambdaJava25WithHibernateAndAuroraDSQL 
  Sample SAM Template

Parameters:
  Stage:
    Type: String
    Default: prod
    
    
Globals:
  Function:
    CodeUri: target/aws-lambda-java-25-with-hibernate-and-aurora-dsql-1.0.0-SNAPSHOT.jar
    Runtime: java25
    SnapStart:
      ApplyOn: PublishedVersions     
    Timeout: 30 
    MemorySize: 1024
    Architectures:
      #- arm64
      - x86_64  
    #Tracing: Active
    Environment:
      Variables:
        AURORA_DSQL_CLUSTER_ENDPOINT: !Sub ${DSQL}.dsql.${AWS::Region}.on.aws
        JAVA_TOOL_OPTIONS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
        
             
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      #TracingEnabled: true
      Name: AWSLambdaJava25WithHibernateAndAuroraDSQLAPI 
      Description: API for AWSLambdaJava25WithHibernateAndDSQL
      AccessLogSetting:
        DestinationArn: !Sub ${MyApiLogGroup.Arn} # This Log Group is already created within our SAM Template
        Format: "{'integrationLatency':'$context.integrationLatency', 'latency':'$context.responseLatency', 'requestId':'$context.requestId', 'ip': '$context.identity.sourceIp', 'caller':'$context.identity.caller', 'user':'$context.identity.user','requestTime':'$context.requestTime', 'xrayTraceId':'$context.xrayTraceId', 'wafResponseCode':'$context.wafResponseCode', 'httpMethod':'$context.httpMethod','resourcePath':'$context.resourcePath', 'status':'$context.status','protocol':'$context.protocol', 'responseLength':'$context.responseLength' }"
      MethodSettings:
        - MetricsEnabled: True
          ResourcePath: '/*'
          HttpMethod: '*'
      Auth:
        ApiKeyRequired: true  # sets for all methods
  
        
  MyApiLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
       LogGroupName: !Sub "/aws/apigateway/${MyApi}"
       RetentionInDays: 7
      
  MyApiUsagePlan:
     Type: AWS::ApiGateway::UsagePlan
     DependsOn:  
        - MyApiStage
     Properties:
      ApiStages: 
        - ApiId: !Ref MyApi
          Stage: !Ref Stage
      UsagePlanName: AWSLambdaJava25WithHibernateAndAuroraDSQLUsagePlan 
      Description: Usage plan for AWSLambdaJava25WithHibernateAndAuroraDSQLAPI
      Quota:
          Limit: 2000000
          Period: DAY
      Throttle:
          RateLimit:  10000
          BurstLimit: 5000   

  MyApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn:  
       - MyApiStage
    Properties: 
      Name: "AWSLambdaJava25WithHibernateAndAuroraDSQLAPIKey"
      Description: "AWSLambdaJava25WithHibernateAndAuroraDSQL API Key"
      Enabled: true
      GenerateDistinctId: false
      Value: a6ZbcDefQW12BN56WEHADQ25
      StageKeys:
        - RestApiId: !Ref MyApi
          StageName: !Ref Stage

  MyApiUsagePlanKey:
      Type: "AWS::ApiGateway::UsagePlanKey"
      DependsOn: 
      - MyApi
      Properties:
        KeyId: !Ref MyApiKey
        KeyType: API_KEY
        UsagePlanId: !Ref MyApiUsagePlan


  PostProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostProductJava25WithHibernateAndDSQL 
      AutoPublishAlias: liveVersion 
      Handler: software.amazonaws.example.product.handler.CreateProductHandler::handleRequest
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                  - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}              
   
      Events:
        PutRequest:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products
            Method: post

  
  PostProductFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${PostProductFunction}"
      RetentionInDays: 7


  GetProductByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProductByIdJava25WithHibernateAndDSQL
      AutoPublishAlias: liveVersion 
      Handler: software.amazonaws.example.product.handler.GetProductByIdHandler::handleRequest
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                 - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}

      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /products/{id}
            Method: get     
            

  GetProductByIdFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdFunction}"
      RetentionInDays: 7


  GetProductByIdWithAuroraPrimingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProductByIdJava25WithHibernateAndDSQLAndDSQLPriming
      AutoPublishAlias: liveVersion 
      Handler: software.amazonaws.example.product.handler.GetProductByIdWithDSQLPrimingHandler::handleRequest
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                 - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}

      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /productsWithAuroraPriming/{id}
            Method: get     
            

  GetProductByIdWithAuroraPrimingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdWithAuroraPrimingFunction}"
      RetentionInDays: 7


  GetProductByIdWithFullPrimingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetProductByIdJava25WithHibernateAndDSQLAndFullPriming
      AutoPublishAlias: liveVersion
      Handler: software.amazonaws.example.product.handler.GetProductByIdWithFullPrimingHandler::handleRequest
      Policies:
          Statement:
            - Effect: Allow
              Action:
                - dsql:DbConnectAdmin
              Resource: 
                 - !Sub arn:${AWS::Partition}:dsql:${AWS::Region}:${AWS::AccountId}:cluster/${DSQL}

      Events:
        GetRequestById:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /productsWithFullPriming/{id}
            Method: get     
            
            
  GetProductByIdWithFullPrimingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetProductByIdWithFullPrimingFunction}"
      RetentionInDays: 7


  DSQL:
    Type: AWS::DSQL::Cluster
    Properties:
      DeletionProtectionEnabled: true 

Outputs:
  AWSLambdaJava25WithHibernateAndDSQLAPIEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for AWS Lambda Java 25, Hibernate and Aurora DSQL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/product"
